### ISSUE TITLE
app crashes when rotated

### ISSUE THREAD

**Issue by giuliohome** [giuliohome/MyOpenTweet2019#1]
App crashing when I rotate the phone!
Please help me and contribute to fix it 🔧 on #github

**Comment by giuliohome** [comment]
Found what is causing the crash by debugging during the async count loop and rotating the phone in the meantime.
So it appears to be a unque constraint violation in sqlite dao insert
```
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
     Caused by: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: word_table.word (code 1555)
    #################################################################
    Error Code : 1555 (SQLITE_CONSTRAINT_PRIMARYKEY)
    Caused By : Abort due to constraint violation.
    	(UNIQUE constraint failed: word_table.word (code 1555))
    #################################################################
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:930)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.arch.persistence.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:50)
        at android.arch.persistence.room.EntityInsertionAdapter.insert(EntityInsertionAdapter.java:64)
        at com.wordpress.giuliohome.testviewmodel.data.WordDao_Impl.insert(WordDao_Impl.java:58)
        at com.wordpress.giuliohome.testviewmodel.data.WordRepository$insertAsyncTask.doInBackground(WordRepository.kt:42)
        at com.wordpress.giuliohome.testviewmodel.data.WordRepository$insertAsyncTask.doInBackground(WordRepository.kt:38)
        at android.os.AsyncTask$2.call(AsyncTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        	... 4 more
```

**Comment by giuliohome** [comment]
Fixed by myself (#kotlin on #slack was useless)
